apiVersion: v2
name: access-node
description: Umbrella Chart for the DOME Marketplace access-node
type: application
version: 1.2.0-PRE-87
appVersion: 0.0.1
dependencies:
  - name: desmos
    condition: desmos.enabled
    repository: https://in2workspace.github.io/helm-charts
    version: 1.1.3
  - name: dlt-adapter
    condition: dlt-adapter.enabled
    repository: https://alastria.github.io/helm-charts
    version: 8.0.0
  - name: kafka
    condition: kafka.enabled
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 26.0.0
  - name: postgresql
    condition: postgis.enabled
    alias: postgis
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 13.1.5
  - name: postgresql
    condition: postgresql.enabled
    alias: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 13.1.5
  - name: scorpio-broker-aaio
    condition: scorpio.enabled
    alias: scorpio
    repository: https://fiware.github.io/helm-charts
    version: 0.4.9
  - name: tm-forum-api
    condition: tm-forum-api.enabled
    repository: https://fiware.github.io/helm-charts
    version: 0.14.14
